---
title: "What tells you that you have a heart disease?"
subtitle: "An analysis of Heart Disease indicators"
author: 
  - Puyu Liu (1005092971)
thanks: "Code and data are available at: https://github.com/liupuyu2/Puyu-Liu."
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "This paper analyzed the data of personal key indicators of heart disease. The result indicates that age, sex, BMI, etc are correlated to having a heart disease.  Based on the analysis, this paper consists of a linear regression analysis, with the use of the programming language R. Keywords: Heart Diseases, Physical health, Mental Health, kaggle, age & sex, stroke, Smoking, Alcohol Drinking"
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(palmerpenguins)
```

# Introduction

As heart diseases have caused most deaths for people in the US, this dataset include about 20 variables that involve several risk factors of heart disease. Around half of all americans have at least one heart disease indicator: blood pressure, high cholesterol, smoking, alcohol drinking, diabete and obesity (high BMI), physical and mental health. Hopefully we can derive a regression analysis to use the logistic regression model to make future predictions for population with heart disease risk factors. Computational developments have a great effect on detecting the early stage of some typical heart diseases.

The paper starts with an overview of the data with 300 thousands observations. And also, we will look into the correlation of every variable then try to conduct a regression analysis. Before that, the dataset should be properly cleaned and outliers and leverage should be well taken care of. After processing the data, we will be using the ANOVA test to determine our variables in our model.



# Data



# Model




# Results

# Discussion

## First discussion point


## Second discussion point

## Third discussion point

## Weaknesses and next steps



\newpage

\appendix

# Appendix {-}


# Additional details


\newpage


# References


